# Layer configuration for meta-pagespeak
# PageSpeak: portable OCR-to-speech device for visually impaired users

BBPATH .= ":${LAYERDIR}"

BBFILES += " \
    ${LAYERDIR}/recipes-*/*/*.bb \
    ${LAYERDIR}/recipes-*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "meta-pagespeak"
BBFILE_PATTERN_meta-pagespeak = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-pagespeak = "10"

LAYERDEPENDS_meta-pagespeak = "core raspberrypi openembedded-layer multimedia-layer"
LAYERSERIES_COMPAT_meta-pagespeak = "kirkstone"
